[workspace]
resolver = "2"
members = [ "lastodo-config","lastodo-main"]
default-members = ["lastodo-main"]

[workspace.dependencies]
chrono = "0.4.38"
color-eyre = "0.6.3"
crossterm = "0.27.0"
indexmap = "2.2.6"
ratatui = { version = "0.26.2", features = ["all-widgets"] }
